# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5 # Supply chain attack mitigation - limit update frequency

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5           # General update frequency control
      semver-major-days: 30     # Breaking changes - extended review period
      semver-minor-days: 7      # Feature additions - moderate review period
      semver-patch-days: 3      # Security fixes - faster but still controlled
