name: Coverage Report

on:
  workflow_run:
    workflows: ["build test"]
    branches: [main]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: c3749199cb455f8b15b130f34f7e327ddc9007590d064270cbfee1009c1c63ec
        with:
          coverageCommand: npm run coverage
